### ISSUE TITLE
[bug] indexError

### ISSUE THREAD

**Issue by Vyogami** [Gaurav-Van/Chat-With-PDF#1]
## Description 

Filesize: 130.2MB

it arises after the submitting the file

![Screenshot_20240516-093749.png](https://github.com/Gaurav-Van/Chat-With-PDF/assets/70915754/b8e0260e-1200-47a2-9fd3-dbfd6814ec96)

### Traceback

> IndexError: This app has encountered an error. The original error message is redacted to prevent data leaks. Full error details have been recorded in the logs (if you're on Streamlit Cloud, click on 'Manage app' in the lower right of your app).

```shell
File "/home/adminuser/venv/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
File "/mount/src/chat-with-pdf/app.py", line 129, in <module>
    main()
File "/mount/src/chat-with-pdf/app.py", line 122, in main
    vectorstore = get_vector_store(text_chunks)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/mount/src/chat-with-pdf/app.py", line 34, in get_vector_store
    vectorstore = FAISS.from_texts(texts=text_chunks, embedding=embeddings)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/adminuser/venv/lib/python3.11/site-packages/langchain_community/vectorstores/faiss.py", line 931, in from_texts
    return cls.__from(
           ^^^^^^^^^^^
File "/home/adminuser/venv/lib/python3.11/site-packages/langchain_community/vectorstores/faiss.py", line 888, in __from
    index = faiss.IndexFlatL2(len(embeddings[0]))
                                  ~~~~~~~~~~^^^
```

**Comment by Gaurav-Van** [comment]
Thanks for raising this issue. Is your file scanned? If yes, then Pdf Reader won't be able to read it and there will be no chunks for embeddings to work on.

**Comment by Vyogami** [comment]
> Thanks for raising this issue. Is your file scanned? If yes, then Pdf Reader won't be able to read it and there will be no chunks for embeddings to work on. 

Oh that makes sense! but it should handle the exception for better user experience.

**Comment by Gaurav-Van** [comment]
Yes, I should’ve handled this particular exception. Not sure how it slipped through, thanks for catching that. 
The code now handles this particular exception.
